<?php

namespace Database\Seeders;

use App\Models\Competence;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CompetencesSeeder extends Seeder
{
    public function run(): void
    {
        $competences = [

            // ── Développement Backend ──────────────────────────────────────
            'PHP', 'Laravel', 'Symfony', 'CodeIgniter',
            'Python', 'Django', 'Flask', 'FastAPI',
            'Java', 'Spring Boot',
            'Ruby on Rails',
            'C#', '.NET', 'ASP.NET',
            'Node.js', 'Express.js', 'NestJS',
            'Go (Golang)', 'Rust', 'C', 'C++',
            'Kotlin (Backend)', 'Scala',

            // ── Développement Frontend ─────────────────────────────────────
            'JavaScript', 'TypeScript',
            'Vue.js', 'React', 'Angular', 'Next.js', 'Nuxt.js',
            'Svelte', 'Astro',
            'HTML', 'CSS', 'Bootstrap', 'Tailwind CSS', 'jQuery',
            'Sass / LESS', 'Webpack', 'Vite',
            'Redux', 'Pinia', 'Zustand',
            'Webflow', 'WordPress', 'WooCommerce', 'Shopify',
            'Joomla', 'Drupal', 'PrestaShop', 'Magento',

            // ── Mobile ─────────────────────────────────────────────────────
            'Flutter', 'React Native',
            'Swift', 'Kotlin (Android)',
            'Ionic', 'Capacitor', 'Expo',
            'Android Studio', 'Xcode',

            // ── Bases de données ───────────────────────────────────────────
            'MySQL', 'PostgreSQL', 'MongoDB', 'Redis',
            'SQLite', 'Oracle', 'SQL Server',
            'Firebase Firestore', 'Supabase',
            'Elasticsearch', 'CassandraDB',

            // ── API & Intégrations ─────────────────────────────────────────
            'REST API', 'GraphQL', 'WebSocket',
            'Postman', 'Swagger / OpenAPI',
            'Stripe / Paiement en ligne', 'FedaPay', 'Monetbil',

            // ── DevOps & Cloud ─────────────────────────────────────────────
            'Git', 'GitHub', 'GitLab', 'Bitbucket',
            'Docker', 'Kubernetes', 'CI/CD',
            'AWS', 'Azure', 'GCP', 'Firebase',
            'Nginx', 'Apache', 'Terraform', 'Ansible',
            'Jenkins', 'GitHub Actions', 'GitLab CI',

            // ── Administration Système / Réseaux ──────────────────────────
            'Linux', 'Ubuntu', 'Bash / Shell scripting',
            'Windows Server', 'Active Directory',
            'Cisco / Routage / Commutation', 'Réseaux TCP/IP',
            'VPN / VoIP', 'Pare-feu / Firewall',
            'Cybersécurité', 'Pentest / Ethical hacking',
            'SIEM / SOC', 'ISO 27001', 'RGPD',
            'Virtualisation (VMware / Hyper-V)',
            'Administration réseau', 'Monitoring réseau',

            // ── IoT & Embarqué ─────────────────────────────────────────────
            'IoT / Internet des objets',
            'Raspberry Pi', 'Arduino', 'Microcontrôleurs',
            'Électronique embarquée',

            // ── Blockchain & Web3 ──────────────────────────────────────────
            'Blockchain', 'Solidity', 'Smart Contracts',
            'Web3.js', 'Cryptomonnaies',

            // ── Data & Business Intelligence ───────────────────────────────
            'Excel', 'Google Sheets', 'Power BI', 'Tableau',
            'Looker Studio', 'Microsoft Fabric',
            'R', 'Pandas', 'NumPy', 'Matplotlib',
            'Machine Learning', 'Deep Learning',
            'TensorFlow', 'PyTorch', 'Scikit-learn',
            'Data Analysis', 'Statistiques',
            'Big data / Hadoop / Spark',
            'Data Engineering / Pipelines',
            'NLP / Traitement du langage naturel',
            'Computer Vision', 'LLM / GPT / IA générative',

            // ── Outils bureautiques & Collaboration ───────────────────────
            'Microsoft Office 365', 'Word', 'PowerPoint',
            'Notion', 'Airtable', 'Trello', 'Jira',
            'Asana', 'Monday.com', 'ClickUp',
            'Slack', 'Microsoft Teams', 'Zoom',
            'Google Workspace', 'SharePoint',
            'Power Automate / Power Apps',
            'SAP', 'Odoo', 'Sage', 'QuickBooks',
            'HubSpot', 'Salesforce', 'Zoho CRM',

            // ── Design / Multimédia ────────────────────────────────────────
            'Figma', 'Adobe XD', 'Sketch',
            'Photoshop', 'Illustrator', 'InDesign', 'After Effects',
            'Premiere Pro', 'DaVinci Resolve', 'Final Cut Pro',
            'Lightroom', 'Canva',
            'CapCut / Montage vidéo mobile',
            'Motion design / Animation 2D-3D',
            'Blender / 3D Studio Max',
            'Design UX / User research',
            'Design UI / Maquettage',
            'Architecture de l\'information',
            'Test utilisateur / UX research',

            // ── Gestion de projet ──────────────────────────────────────────
            'Gestion de projet', 'PMP', 'PRINCE2', 'PMI',
            'Scrum', 'Agile', 'Kanban', 'SAFe',
            'Lean Management', 'Six Sigma',
            'OKR', 'KPI', 'Reporting',
            'Change management / Conduite du changement',
            'Risk management / Gestion des risques',
            'Business analysis / AMOA',
            'Étude de faisabilité',
            'Gestion de portefeuille de projets (PMO)',
            'Planning MS Project',

            // ── Marketing Digital ──────────────────────────────────────────
            'SEO / Référencement naturel', 'SEA / Google Ads',
            'Meta Ads / Facebook Ads',
            'TikTok Marketing', 'LinkedIn Marketing',
            'Social Media Marketing', 'Community management',
            'Content Marketing / Stratégie de contenu',
            'Email Marketing / Newsletter',
            'Inbound marketing', 'Growth hacking',
            'Influence marketing', 'Affiliation',
            'Google Analytics / GA4',
            'Copywriting', 'Storytelling', 'Rédaction web / Blog',
            'Brand management / Branding',
            'Marketing événementiel',
            'Relations presse / RP',
            'Communication de crise',
            'Marketing B2B', 'Marketing B2C',
            'CRM Marketing', 'Marketing automation',
            'Webinaires / Lives streaming',
            'Création de contenu vidéo / TikTok / Reels',

            // ── Commerce & Ventes ──────────────────────────────────────────
            'Prospection commerciale',
            'Vente BtoB', 'Vente BtoC',
            'Négociation commerciale', 'Closing / Signature',
            'Fidélisation client', 'Gestion de portefeuille clients',
            'Merchandising', 'Commerce de terrain',
            'Développement commercial',
            'Key Account Management (KAM)',
            'Export / Commerce international',
            'Vente en ligne / E-commerce',
            'Pricing / Politique tarifaire',
            'CRM / Gestion de la relation client',
            'Force de vente / Animation réseau',
            'Distribution / Mise en rayon',

            // ── Finance & Comptabilité ─────────────────────────────────────
            'Comptabilité générale', 'Comptabilité SYSCOHADA',
            'Comptabilité analytique', 'Comptabilité publique',
            'Fiscalité / Déclarations fiscales',
            'Audit interne', 'Audit externe',
            'Contrôle de gestion', "Finance d'entreprise",
            'Analyse financière', 'Trésorerie / Cash management',
            'Consolidation des comptes',
            'Gestion budgétaire / Budget prévisionnel',
            'Analyse de crédit / Scoring',
            'Évaluation d\'entreprise / Due diligence',
            'Modélisation financière / Excel avancé',
            'Microfinance / Gestion de portefeuille crédit',
            'Mobile money / Wave / Orange Money / MTN',
            'Plan d\'affaires / Business plan',
            'Gestion de patrimoine',
            'OHADA / Droit comptable OHADA',

            // ── Ressources Humaines ────────────────────────────────────────
            'Recrutement / Talent acquisition',
            'Formation professionnelle', 'Ingénierie de formation',
            'Gestion de la paie / Bulletin de salaire',
            'Droit du travail', 'Droit social',
            'SIRH / Logiciels RH', 'GPEC / GEPP',
            'Évaluation des performances / Entretiens annuels',
            'Onboarding / Intégration des collaborateurs',
            'Marque employeur / Employer branding',
            'Relations sociales / IRP / Partenaires sociaux',
            'Coaching professionnel', 'Mentorat',
            'Management interculturel',
            'Management à distance / Télétravail',
            'Tableau de bord RH / Bilan social',
            'Politique de rémunération',
            'Médiation / Résolution de conflits',

            // ── Droit & Juridique ──────────────────────────────────────────
            'Droit des affaires', 'Droit OHADA',
            'Droit civil', 'Droit pénal',
            'Droit administratif', 'Droit constitutionnel',
            'Droit fiscal', 'Droit du travail',
            'Droit de l\'environnement',
            'Droit international / Droit communautaire CEDEAO',
            'Contentieux / Plaidoirie',
            'Rédaction de contrats / Actes juridiques',
            'Conseil juridique / Compliance',
            'Propriété intellectuelle / Brevets',
            'Arbitrage / Médiation / CCJA',
            'Droit foncier / Notariat',
            'Droit de l\'immobilier',

            // ── Agriculture & Agronomie ────────────────────────────────────
            'Agronomie / Sciences du sol',
            'Phytotechnie / Production végétale',
            'Zootechnie / Production animale',
            'Agroforesterie / Reboisement',
            'Agriculture biologique / Certification bio',
            'Irrigation / Hydraulique agricole',
            'Protection des plantes / Phytosanitaire',
            'Transformation agroalimentaire / Conserverie',
            'Élevage bovin / Ovin / Caprin',
            'Aviculture / Élevage de volaille',
            'Pisciculture / Aquaculture',
            'Apiculture / Production de miel',
            'Culture du coton / Anacarde / Palmier à huile',
            'Maraîchage / Cultures légumières / Jardinage',
            'Stockage post-récolte / Silo',
            'Vulgarisation agricole / Conseil agricole',
            'SIG agricole / Cartographie des terres',
            'FIDA / FAO / Projets agricoles',

            // ── BTP / Génie civil / Architecture ──────────────────────────
            'Dessin technique / AutoCAD',
            'SketchUp', 'Revit / BIM',
            'Béton armé / Calcul de structures',
            'Métrés / Devis / Estimation de travaux',
            'Conduite de chantier / Suivi de travaux',
            'Gestion de chantier / Planning travaux',
            'Topographie / Géomètre',
            'Plomberie / Sanitaire',
            'Électricité bâtiment / Câblage',
            'Menuiserie bois / Charpente',
            'Menuiserie aluminium / PVC',
            'Carrelage / Faïence',
            'Peinture en bâtiment',
            'Maçonnerie / Ferraillage',
            'Couverture / Étanchéité / Zinguerie',
            'Climatisation / Réfrigération',
            'Sécurité chantier / HSE BTP',
            'Études géotechniques / Sondages',
            'Voirie et réseaux divers (VRD)',

            // ── Santé & Médical ────────────────────────────────────────────
            'Soins infirmiers / Nursing',
            'Gynécologie / Obstétrique / Maternité',
            'Pédiatrie / Néonatologie',
            'Médecine interne / Généraliste',
            'Chirurgie générale / Orthopédique',
            'Radiologie / Imagerie médicale',
            'Cardiologie / Échocardiographie',
            'Neurologie / Neurochirurgie',
            'Dermatologie / Vénérologie',
            'Stomatologie / Chirurgie dentaire',
            'Ophtalmologie / Optique médicale',
            'Kinésithérapie / Rééducation',
            'Pharmacologie / Gestion médicaments',
            'Biologie médicale / Analyses de laboratoire',
            'Épidémiologie / Santé publique',
            'Nutrition / Diététique / Alimentation',
            'Hygiène / Assainissement / WASH',
            'Médecine du travail',
            'Urgences / Réanimation / SMUR',
            'Anesthésie-réanimation',
            'Psychologie clinique / Santé mentale',
            'Sage-femme / Maïeutique',
            'Médecine communautaire / Agents de santé',
            'Médecine vétérinaire',
            'Santé animale / One Health',

            // ── Transport & Logistique ─────────────────────────────────────
            'Conduite poids lourds / Transport de marchandises',
            'Transport de personnes / VTC / Taxi',
            'Gestion de stock / Inventaire',
            'Dédouanement / Déclaration en douane',
            'Freight forwarding / Transit',
            'Gestion d\'entrepôt / WMS',
            'Chaîne du froid / Cold chain',
            'Planification des tournées / Routage',
            'Conduite de chariot élévateur / CACES',
            'Pilote de drone / UAV',
            'Navigation maritime / Capitaine de bord',
            'Logistique humanitaire',
            'Gestionnaire de flotte',

            // ── Énergie & Environnement ────────────────────────────────────
            'Installation solaire photovoltaïque',
            'Électricité rurale / Off-grid',
            'Audit énergétique / Efficacité énergétique',
            'Forage / Hydraulique villageoise',
            'Évaluation environnementale / EIE',
            'Changement climatique / Adaptation',
            'Gestion des déchets / Collecte / Tri',
            'Reboisement / Plantation',
            'REDD+ / Crédit carbone',
            'SIG / Cartographie environnementale',
            'Eau et assainissement / WASH',

            // ── Hôtellerie / Tourisme / Restauration ──────────────────────
            'Réception hôtelière / Accueil',
            'Service en salle / Restauration',
            'Cuisine / Arts culinaires / Gastronomie',
            'Pâtisserie / Boulangerie',
            'Barman / Mixologie / Cocktails',
            'Housekeeping / Gouvernante d\'hôtel',
            'Revenue management hôtelier',
            'Guide touristique / Interprète',
            'Organisation de voyages / Tour opérateur',
            'MICE / Tourisme d\'affaires',
            'Agritourisme / Écotourisme',

            // ── Médias / Audiovisuel / Arts ────────────────────────────────
            'Journalisme / Reportage terrain',
            'Journalisme radio / Présentateur radio',
            'Présentateur TV / JT / Animateur',
            'Rédacteur en chef / Chef de rubrique',
            'Montage vidéo / Post-production',
            'Réalisation / Mise en scène',
            'Prise de son / Ingénieur du son',
            'Photojournalisme / Reportage photo',
            'Illustration / Bande dessinée / BD',
            'Scénographie / Décoration de plateau',
            'Danse / Chorégraphie',
            'Chant / Musique traditionnelle béninoise',
            'Composition musicale / Production musicale',

            // ── Mode & Beauté & Artisanat ──────────────────────────────────
            'Stylisme / Couture / Modélisme',
            'Création wax / Tissu africain',
            'Broderie / Couture traditionnelle',
            'Coiffure / Tresses africaines',
            'Barbier / Coiffure homme',
            'Esthétique / Maquillage / Nail art',
            'Massage / Spa / Soins du corps',
            'Bijouterie / Joaillerie',
            'Poterie / Céramique / Sculpture',
            'Vannerie / Cordonnerie',
            'Teinture / Batik / Tie-dye',

            // ── Éducation & Formation ──────────────────────────────────────
            'Pédagogie / Didactique',
            'Ingénierie pédagogique',
            'Conception de curriculum / Programmes',
            'Enseignement des mathématiques',
            'Enseignement des sciences (SVT / Physique)',
            'Enseignement du français / Linguistique',
            'Enseignement de l\'anglais / TEFL',
            'Enseignement des langues locales (fon, yoruba, dendi, bariba)',
            'Formation des formateurs / Train the trainer',
            'Évaluation des apprentissages',
            'Éducation inclusive / Pédagogie spécialisée',
            'Gestion d\'établissement scolaire',
            'Tutorat / Soutien scolaire',
            'Alphabétisation des adultes',
            'EFTP / Enseignement technique et professionnel',

            // ── Qualité / HSE / Sécurité ───────────────────────────────────
            'ISO 9001 / Management de la qualité',
            'ISO 14001 / Management environnemental',
            'ISO 45001 / Sécurité au travail (OHSAS)',
            'HSE / Hygiène Sécurité Environnement',
            'HACCP / Sécurité alimentaire',
            'Contrôle qualité / Inspection produits',
            'Lean Six Sigma / Amélioration continue',
            'Audit qualité / Certification',
            'Accréditation / Normes ISO',

            // ── Administration & Secteur public ───────────────────────────
            'Administration publique / Gestion de l\'État',
            'Gestion des collectivités locales',
            'Passation de marchés publics / ARMP',
            'Rédaction administrative / Courriers officiels',
            'Gestion du budget de l\'État / SIGFIP',
            'Contrôle financier / IGE / IGF',
            'Planification du développement local',
            'Relations institutionnelles',
            'Protocole diplomatique',
            'Politique publique / Analyse des politiques',

            // ── Soft Skills & Compétences transversales ────────────────────
            'Leadership', "Management d'équipe",
            'Communication orale et écrite',
            'Présentation / Prise de parole en public',
            'Négociation', 'Médiation et résolution de conflits',
            'Travail en équipe / Collaboration',
            'Adaptabilité / Flexibilité',
            'Créativité / Pensée innovante',
            'Esprit critique / Analyse',
            'Résolution de problèmes complexes',
            'Gestion du stress / Résilience',
            'Rigueur / Organisation / Méthode',
            'Autonomie / Initiative',
            'Sens du service client',
            'Ponctualité / Fiabilité / Engagement',
            'Intelligence émotionnelle',
            'Networking / Développement de partenariats',
            'Gestion du temps / Priorisation',
            'Rédaction professionnelle / Rapports',
            'Entrepreneuriat / Esprit startup',
            'Sensibilité interculturelle',
            'Veille stratégique / Benchmark',

            // ── Langues étrangères (comme compétence professionnelle) ───────
            'Anglais professionnel / Business English',
            'Français professionnel',
            'Portugais', 'Espagnol', 'Allemand',
            'Arabe', 'Chinois mandarin',
            'Fon', 'Yoruba', 'Dendi', 'Bariba', 'Mina / Goun',
            'Traduction / Interprétariat',
        ];

        foreach ($competences as $nom) {
            Competence::firstOrCreate(
                ['slug' => Str::slug($nom)],
                ['nom'  => $nom]
            );
        }
    }
}
